# Generated by Django 4.2.7 on 2023-11-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
