# Generated by Django 4.2.7 on 2023-11-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dueDate',
            field=models.CharField(max_length=10),
        ),
    ]
