# Generated by Django 4.2.7 on 2023-11-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dueDate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
